jobs:
- job: Build
  condition: eq(variables['Build.Reason'], 'Manual')
  displayName: Build
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      command: build
      dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      tags: |
        $(tag)
